CREATE DATABASE SESION
GO


--CREAR TABLA DE USUARIOS
CREATE TABLE USUARIOS
(
	IDROL INT PRIMARY KEY IDENTITY,
	USUARIO NVARCHAR(50)NOT NULL,
	CONTRASEÑA NVARCHAR(50)NOT NULL,

);

INSERT INTO USUARIOS(USUARIO,CONTRASEÑA)
VALUES ('Tito', '1234');

